version: '3.3'

services:
  elasticsearch:
    # docker exec しやすいようにコンテナ名を指定
    container_name: elasticsearch

    # 公式イメージを使う
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.1

    # 標準のポートを同じ番号でホストに公開
    # <host>:<container>
    ports:
      - 9200:9200

  kibana:
    # docker exec しやすいようにコンテナ名を指定
    container_name: kibana

    # 公式イメージを使う
    image: docker.elastic.co/kibana/kibana:5.5.1

    # elasticsearch コンテナと elasticsearch というホスト名で接続できるようにする
    # <host>:<container>
    links:
      - elasticsearch:elasticsearch

    # 標準のポートを同じ番号でホストに公開
    # <host>:<container>
    ports:
      - 5601:5601

    # kibana の設定ファイルをコンテナ実行時に渡す
    # <host>:<container>
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml

  twitter_crawler:
    # Dockerfile からビルド
    build: ./twitter_crawler

    # docker exec しやすいようにコンテナ名を指定
    container_name: twitter_crawler

    # elasticsearch コンテナと elasticsearch というホスト名で接続できるようにする
    # <host>:<container>
    links:
      - elasticsearch:elasticsearch

    # スクリプトをコンテナ実行時に渡す
    # <host>:<container>
    volumes:
      - ./twitter_crawler/scripts:/root/scripts
